name: arweave
description: 
version: 0.1.0
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cryptography: ^2.0.5
  http: ^0.13.5
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  jwk: ^0.1.1
  meta: ^1.8.0
  pointycastle: ^3.6.2

dev_dependencies:
  build_runner: ^2.3.2
  pedantic: ^1.11.1
  test: ^1.22.0 

dependency_overrides:
  crypto: ^3.0.0-nullsafety.0
